/*******************************************************************************
 * Copyright (c) 2011, Tomato System and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * This file was generated by pde-tools.
 *
 * pde-tools was developed as a part of eXERD by jeeeyul@gmail.com
 *
 * http://code.google.com/p/pde-tools
 * http://eclipse.or.kr
 * http://exerd.com
 * http://tomatosystem.co.kr
 *
 * Contributors:
 *     Tomato System - initial API and implementation
 *******************************************************************************/
 
package net.jeeeyul.pdetools.shared; 

import java.net.URL;
import java.util.HashMap;

import org.eclipse.core.runtime.Platform;
import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.swt.graphics.Image;
import org.eclipse.ui.ISharedImages;
import org.eclipse.ui.PlatformUI;
public class SharedImages{
	/**
	 * <img src="data:image/gif;base64,R0lGODlhEAAQANUAADV2VDh6Vzh5Vzt+Wjx+WkCFXkSLYkWMY0WLYkWLY0WMYkqTZ0qTaE+abFCabFShcVWhcVShcFindVWicVyseV+we12seY20U420VJa5VZa5VqDAWKHAWKzHWqzHW63HWq3GWq3HW8XWYMbWYMXVYMbVYMXVYdDbY9riZdrhZeDlZv///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACsALAAAAAAQABAAAAZbwJVwSCwaj0hhZVlJDisqVdO5oqRQFupKcpUgJxHI40Q+Pc4PokMkMpHapRG7QWSEQqAOKOT5+BdEBgkKChscGxsKCAcHSAUZGgVaBBgXA1oBlQJaAJ0AWqCgQQA7" align="middle" />
	 * Constant for "icons/add.gif" file.
	 */
	public static final String ADD = "icons/add.gif";

	/**
	 * <img src="data:image/gif;base64,R0lGODlhEAAQAOYAAC0rTzpIZzZGZT9ObAAocgAocTBDZDJEZTdHZTtLZzxLZzBGajFHajJIazJHajVKbDNGZDRGZThObrK7x7jD0CVvviZvvihxvyVwvip0wip0wStzvi10vi51vy92v1BsiFJuij51pkJ4qDRwpDRwozVxpUB3pwdYmApamT2GvDyGuz6Hu0KJvESMvUWNvVKZwPf8/06Yv0+Yv1OawPb8//X8//f9//X9//n+//3//6LEv6TFwKTDvqXHwdPp5dHn49Lp5NHo46jIwMrpv8ztv8vsv8vpv8/xweru5+nt5fj/vf//xv//1f//28PBlsnEmMXBl+3s4vb05ff15+nkz+Xgzenjz/Tw4/Lu4+nhz////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAFsALAAAAAAQABAAAAeAgFuCg4SFhoeGABRIQSosK1iIFBIPT0ACVRYvQ4ZID00NWqJFATGGP08NTAtOWgY6GFGFKT5aDEsMNqJWG4UsCFpQDkoFWhAKLoUrPDA0SQQTODlCHoVRFUQHWjQ1ET0aUoYyATvGN0cDH4dGMxdZCVQZIIiCVxwtHVP0+/z9/YEAOw==" align="middle" />
	 * Constant for "icons/configure.gif" file.
	 */
	public static final String CONFIGURE = "icons/configure.gif";

	/**
	 * <img src="data:image/gif;base64,R0lGODlhCQAJAPcAADAxKDk8NUZJPltAKl1CLV9FMWBHMmFIM2NKNmVMOWZOO2hQPGlSP1RSQldZU11hXWtUQmxVQ3FbSnJcS3djUnhjU31qW31rXHp5ZH9+cINxY4NyZIh4a4l5bIB+cIx8cI1+c4+BdZGDeJSGfJaJf5WRf5iLgZqOhKGliKyojbq1nL25ob66pbrBsNO9qcjAp9XOtdjOtN7NuNjVweTZwuvfyevgyf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAACQAJAAAIVQBPmCAxQkQIEB86jLjBsOGNDSBuCGgAIMCDGxc43MCgooQHBzcqaLiRYgUMFhluTLBw40UMGjVm3IhA4QYKFzJstLihQILDhgYgMFiQAMGBAgQGBAQAOw==" align="middle" />
	 * Constant for "icons/image.gif" file.
	 */
	public static final String IMAGE = "icons/image.gif";

	/**
	 * <img src="data:image/gif;base64,R0lGODlhEAAQAPcAAAAAAFNMHlJNIFRUN1NXOVRUOFVXOVVVPlRXP1dZOkFIR0tLQE1RQUtQSVNXRVWGvHGDsHGRunGVvXihzY9SGZ5fHZ5mJ6VsJK1sJK1yK61yL7R/Mrx/MryFMoaDfLCHY8OFNsOLNvjQeIKfvKacobanpYyszZKwyJS215m75LzL06vM58ymkdm+tOjQiPjQgPjYiPDYkPjYkPjgmPjomPjgoPjosPjwyP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAP8ALAAAAAAQABAAAAiGAP8JHEiwoMGDCBMaDMEwhMJ/GHDgEJCAgIEBBQwEIAiCBo0YCFacQBFBgokDBDvcWOlAhYcSEB5MYECQg42bC1h8aEFiRIoGBDfUGKpAg9GjSP9lkMFUw4ynUJ+60PDvAgwYGq5q1TpVYAURGl6IHSu2q0AKGkSoXavW7EALcOPKfUi3bkAAOw==" align="middle" />
	 * Constant for "icons/image-folder.gif" file.
	 */
	public static final String IMAGE_FOLDER = "icons/image-folder.gif";

	private static HashMap<String, ImageDescriptor> descMap = new HashMap<String, ImageDescriptor>();
	private static HashMap<String, Image> imageMap = new HashMap<String, Image>();

	public static Image getImage(String key) {
		Image image = imageMap.get(key);
		if (image == null) {
			image = loadImage(key);
			ImageDescriptor descriptor = ImageDescriptor.createFromImage(image);
			descMap.put(key, descriptor);
			imageMap.put(key, image);
		}
		return image;
	}

	public static ImageDescriptor getImageDescriptor(String key) {
		ImageDescriptor descriptor = descMap.get(key);
		if (descriptor == null) {
			Image image = loadImage(key);
			descriptor = ImageDescriptor.createFromImage(image);
			descMap.put(key, descriptor);
			imageMap.put(key, image);
		}
		return descriptor;
	}

	private static Image loadImage(String key) {
		try {
			URL resource = Platform.getBundle("net.jeeeyul.pdetools").getResource(key);
			Image image = new Image(null, resource.openStream());
			return image;
		} catch (Exception e) {
			e.printStackTrace();
			return PlatformUI.getWorkbench().getSharedImages().getImage(ISharedImages.IMG_OBJS_ERROR_TSK);
		}
	}
}